# Generated by Django 6.0.3 on 2026-03-11 01:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del contacto', max_length=100, verbose_name='Nombre completo')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener entre 9 y 15 dígitos, puede incluir + al inicio.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo electrónico')),
                ('direccion', models.TextField(blank=True, help_text='Dirección completa del contacto', max_length=200, null=True, verbose_name='Dirección')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='contactos_fotos/', verbose_name='Foto')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('notas', models.TextField(blank=True, max_length=500, null=True, verbose_name='Notas adicionales')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('favorito', models.BooleanField(default=False, verbose_name='Contacto favorito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-favorito', 'nombre'],
                'unique_together': {('usuario', 'nombre', 'telefono')},
            },
        ),
    ]
