# Generated by Django 6.0.3 on 2026-03-11 01:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contacto',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener entre 10 y 20 caracteres y puede incluir +, espacios o guiones.', regex='^\\+?[\\d\\s-]{10,20}$')], verbose_name='Teléfono'),
        ),
    ]
